# Generated by Django 4.1.3 on 2022-11-20 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_birth_date_alter_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='owner',
        ),
    ]
