# Generated by Django 4.1.3 on 2022-12-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_skills_fav_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='fav_skills',
        ),
    ]
