# Generated by Django 4.1.3 on 2022-11-20 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_alter_profile_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pune',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('perkohshmeri', models.BooleanField(default=False)),
                ('experience', models.CharField(choices=[('Fillestar', 'Fillestar'), ('1-2 vjet pervoje', '1-2 vjet pervoje'), ('3-6 vjet pervoje', '3-6 vjet pervoje'), ('7+ vjet pervoje', '7+ vjet pervoje')], max_length=255)),
                ('pagesa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('orari', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('business', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('skills', models.ManyToManyField(blank=True, to='users.skills')),
            ],
        ),
    ]
