# Generated by Django 4.1.3 on 2022-11-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pune', '0002_pune_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pune',
            name='pagesa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
