# Generated by Django 4.1.3 on 2022-11-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_businessprofile'),
        ('pune', '0003_alter_pune_pagesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pune',
            name='aplicants',
            field=models.ManyToManyField(blank=True, related_name='aplicants', to='users.profile'),
        ),
    ]
