# Generated by Django 4.1.3 on 2022-11-25 13:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pune', '0005_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes',
            new_name='Apliko',
        ),
        migrations.RemoveField(
            model_name='pune',
            name='aplicants',
        ),
    ]
