# Generated by Django 4.1.3 on 2022-11-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pune', '0006_rename_likes_apliko_remove_pune_aplicants'),
    ]

    operations = [
        migrations.AddField(
            model_name='pune',
            name='aplicants',
            field=models.ManyToManyField(blank=True, to='pune.apliko'),
        ),
    ]
