# Generated by Django 4.1.3 on 2022-11-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pune', '0007_pune_aplicants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pune',
            name='aplicants',
        ),
        migrations.AddField(
            model_name='pune',
            name='aplicants',
            field=models.IntegerField(default=0),
        ),
    ]
